go_to_location:
  - {name: "home", frame: "shopdesk", position: [0.690, 0.299, 0.224], quaternion: [0.995, -0.100, -0.000, 0.000]}  
  
go_to_location_server:

  ik_sol_number: 512
  max_stall_iter: 100
  collision_detector: FCL
  planning_time: 5

  groups:
    ur5: tip
     
  ur5:
    preferred_configuration: [1.57, -1.57, 1.57, -1.57, -1.57, 0]
    preferred_configuration_weight: [0, 1, 1, 1, 1, 1]
    max_ik_goal_number: 512
    use_single_goal: false
    #lower_bound: [-3.15, -3.15, -3.15, -3.15, -3.15, -3.15]
    #upper_bound: [3.15, 3.15, 3.15, 3.15, 3.15, 3.15]

  request_adapters:
  - default_planner_request_adapters/AddTimeParameterization
  - default_planner_request_adapters/FixWorkspaceBounds
  - default_planner_request_adapters/FixStartStateBounds
  - default_planner_request_adapters/FixStartStateCollision
  - default_planner_request_adapters/FixStartStatePathConstraints


