inbound:
  boxes:
  - {name: "sp1",            frame: "shopdesk",        position: [ 0.05,  0.2,  0.001],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.15] } 
  - {name: "sp2",            frame: "shopdesk",        position: [ 0.05,  0.1,  0.001],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.05] } 
  - {name: "sp3",            frame: "shopdesk",        position: [ 0.05,  0.0,  0.001],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.05] } 
  - {name: "sp4",            frame: "shopdesk",        position: [ 0.05, -0.1,  0.001],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.05] } 
  - {name: "sp5",            frame: "shopdesk",        position: [ 0.05, -0.2,  0.001],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.05] } 
  - {name: "sg1",            frame: "shopdesk",        position: [ 0.15,  0.35, 0.001],  quaternion: [0.7071068, -0.7071068, -0.000, -0.000], approach_distance: [0, 0, 0.05] } 
  - {name: "sg2",            frame: "shopdesk",        position: [ 0.30,  0.35, 0.001],  quaternion: [0.7071068, -0.7071068, -0.000, -0.000], approach_distance: [0, 0, 0.05] } 
  - {name: "sg3",            frame: "shopdesk",        position: [ 0.45,  0.35, 0.001],  quaternion: [0.7071068, -0.7071068, -0.000, -0.000], approach_distance: [0, 0, 0.05] }  
  - {name: "sg4",            frame: "shopdesk",        position: [ 0.60,  0.35, 0.001],  quaternion: [0.7071068, -0.7071068, -0.000, -0.000], approach_distance: [0, 0, 0.05] } 
  #- {name: "sg1",            frame: "shopdesk",        position: [ 0.15,  0.35, 0.001],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.05] } 
  #- {name: "sg2",            frame: "shopdesk",        position: [ 0.30,  0.35, 0.001],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.05] } 
  #- {name: "sg3",            frame: "shopdesk",        position: [ 0.45,  0.35, 0.001],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.05] }  
  #- {name: "sg4",            frame: "shopdesk",        position: [ 0.60,  0.35, 0.001],  quaternion: [0.0, 0.0, 0.0, 1.0], approach_distance: [0, 0, 0.05] } 
 

inbound_pick_server:

  ik_sol_number: 512
  max_stall_iter: 500
  collision_detector: FCL
  planning_time: 5
  
  groups:
    ur5: tip

  ur5:
    preferred_configuration: [1.57, -1.57, 1.57, -1.57, -1.57, 0]
    preferred_configuration_weight: [0, 1, 1, 1, 1, 1]
    max_ik_goal_number: 512
    use_single_goal: false
    #lower_bound: [-3.15, -3.15, -3.15, -3.15, -3.15, -3.15]
    #upper_bound: [3.15, 3.15, 3.15, 3.15, 3.15, 3.15]

  request_adapters:
  - default_planner_request_adapters/AddTimeParameterization
  - default_planner_request_adapters/FixWorkspaceBounds
  - default_planner_request_adapters/FixStartStateBounds
  - default_planner_request_adapters/FixStartStateCollision
  - default_planner_request_adapters/FixStartStatePathConstraints
