inbound:
  # Inbound boxes locations
  boxes:
  # name: box name
  # frame: reference frame in which the box location is defined
  # position: position of the object  w.r.t. the reference frame
  # quaternion: rotation of the object w.r.t. the reference frame
  # approach_distance: approach and leave distances along x,y,z axes from the location
  - { name: "Los1",            frame: "shopdesk",        position: [ 0.15,  0.2,  0.05],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.15] }
  - { name: "Los2",            frame: "shopdesk",        position: [ 0.15,  0.1,  0.05],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.15] } 
  - { name: "Los3",            frame: "shopdesk",        position: [ 0.15,  0.0,  0.05],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.15] }
  - { name: "Los4",            frame: "shopdesk",        position: [ 0.15, -0.1,  0.05],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.15] }
  - { name: "Los5",            frame: "shopdesk",        position: [ 0.15, -0.2,  0.05],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.15] }
  - { name: "Lob1",            frame: "shopdesk",        position: [ 0.30,  0.25, 0.05],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.15] }
  - { name: "Lob2",            frame: "shopdesk",        position: [ 0.45,  0.25, 0.05],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.15] }
  - { name: "Lob3",            frame: "shopdesk",        position: [ 0.60,  0.25, 0.05],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.15] }
  - { name: "Lob4",            frame: "shopdesk",        position: [ 0.75,  0.25, 0.05],  quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, 0.15] }


# inbound_pick_server configurations
inbound_pick_server:

  # number of solutions for the IK
  ik_sol_number: 512
  # maximum stall iterations during the research of the IK
  max_stall_iter: 100
  # name of the collision detector
  collision_detector: FCL
  # planning time
  planning_time: 5

  # names of the move groups to be used for the planning
  groups:
    ur5: tip

  # configurations of the motion planner for a specific move_group
  ur5:
    preferred_configuration: [1.57, -1.57, 1.57, -1.57, -1.57, 0]
    preferred_configuration_weight: [0, 1, 1, 1, 1, 1]
    max_ik_goal_number: 512
    use_single_goal: false
    #lower_bound: [-3.15, -3.15, -3.15, -3.15, -3.15, -3.15]
    #upper_bound: [3.15, 3.15, 3.15, 3.15, 3.15, 3.15]


  request_adapters:
  - default_planner_request_adapters/AddTimeParameterization
  - default_planner_request_adapters/FixWorkspaceBounds
  - default_planner_request_adapters/FixStartStateBounds
  - default_planner_request_adapters/FixStartStateCollision
  - default_planner_request_adapters/FixStartStatePathConstraints
