squadra_grande:
  color: [1,0.8,0,1.]
  mesh: "package://manipulation_skills/mesh/squadra120mm.STL"
  scale: [0.001, 0.001, 0.001]

  offset: [0,0,0] #
  grasp_poses:
  #- {tool: "tip", position: [0, 0, 0.060], quaternion: [0, 0, 0.7071068, 0.7071068 ]}
  #- {tool: "tip", position: [0, 0, 0.060], quaternion: [0, 0, -0.7071068, 0.7071068]}
  - {tool: "tip", position: [0, 0, 0.060], quaternion: [1,0,0,0 ]}
  - {tool: "tip", position: [0, 0, 0.060], quaternion: [0,1,0,0]}

squadra_piccola:
  color: [1,0.8,0,1.]
  box:  [0.08,0.04,0.08]
  mesh: "package://manipulation_skills/mesh/squadra40mm.STL"
  scale: [0.001, 0.001, 0.001]

  offset: [0,0,0] #
  grasp_poses:
  #- {tool: "tip", position: [0, 0, 0.060], quaternion: [0, 0, 0.7071068, 0.7071068 ]}
  #- {tool: "tip", position: [0, 0, 0.060], quaternion: [0, 0, -0.7071068, 0.7071068]}
  - {tool: "tip", position: [0, 0, 0.060], quaternion: [1,0,0,0]}
  - {tool: "tip", position: [0, 0, 0.060], quaternion: [0,1,0,0]}


