objects_description:
  # name of the object to be manipulated
  L_obj_big:
    # color of the object
    color: [1,0.8,0,1.]
    # object STL path
    mesh: "package://manipulation_skills/mesh/squadra120mm.STL"
    # object scaling 
    scale: [0.001, 0.001, 0.001]
    # object offset
    offset: [0,0,0] 

    # grasping postions
    grasp_poses:
    - {tool: "tip", position: [0, 0, 0.060], quaternion: [-0.7071068, 0.7071068, 0, 0]}
    - {tool: "tip", position: [0, 0, 0.060], quaternion: [0.7071068, -0.7071068, 0, 0 ]}

  # name of the object to be manipulated
  L_obj_small:
    # color of the object
    color: [1,0.8,0,1.]
    # object STL path
    mesh: "package://manipulation_skills/mesh/squadra40mm.STL"
    # object scaling
    scale: [0.001, 0.001, 0.001]
    # object offset
    offset: [0,0,0] 

    # grasping postions
    grasp_poses:
    - {tool: "tip", position: [0, 0, 0.060], quaternion: [0.7071068, -0.7071068, 0, 0]}
    - {tool: "tip", position: [0, 0, 0.060], quaternion: [-0.7071068, 0.7071068, 0, 0]}

 
