outbound:
  slots_group:
  - {name: "group_A"}
  - {name: "group_B"}

outbound_place_server:

  ik_sol_number: 512
  max_stall_iter: 100
  collision_detector: FCL
  planning_time: 5

  groups:
    ur5: tip
     
  ur5:
    preferred_configuration: [1.57, -1.57, 1.57, -1.57, -1.57, 0]
    preferred_configuration_weight: [0, 1, 1, 1, 1, 1]
    max_ik_goal_number: 512
    use_single_goal: false
    #lower_bound: [-3.15, -3.15, -3.15, -3.15, -3.15, -3.15]
    #upper_bound: [3.15, 3.15, 3.15, 3.15, 3.15, 3.15]
    
  request_adapters:
  - default_planner_request_adapters/AddTimeParameterization
  - default_planner_request_adapters/FixWorkspaceBounds
  - default_planner_request_adapters/FixStartStateBounds
  - default_planner_request_adapters/FixStartStateCollision
  - default_planner_request_adapters/FixStartStatePathConstraints




