manipulation_object_types:
- {
      "type": "L_obj_big",
      "grasp_poses": [{
          "position": [0, 0, 0.06],
          "quaternion": [-0.7071068, 0.7071068, 0, 0],
          "approach_distance": [0, 0, 0.1],
          "tool": "tip"
      }, {
          "position": [0, 0, 0.06],
          "quaternion": [0.7071068, 0.7071068, 0, 0 ],
          "approach_distance": [0, 0, 0.1],
          "tool": "tip"
      }]
  }
- {
      "type": "L_obj_small",
      "grasp_poses": [{
          "position": [0, 0, 0.06],
          "quaternion": [-0.7071068, 0.7071068, 0, 0],
          "approach_distance": [0, 0, 0.1],
          "tool": "tip"
      }, {
          "position": [0, 0, 0.06],
          "quaternion": [0.7071068, 0.7071068, 0, 0 ],
          "approach_distance": [0, 0, 0.1],
          "tool": "tip"
      }]
  }
