manipulation_object_types:
- {
      "type": "L_obj_big",
      "grasp_poses": [{
          "position": [0, 0, 0.08],
          "quaternion": [ 1, 0, 0, 0 ],
          "approach_distance": [0, 0, -0.1],
          "tool": "tip"
      }]
  }
- {
      "type": "L_obj_small",
      "grasp_poses": [{
          "position": [0, 0, 0.06],
          "quaternion": [ 1, 0, 0, 0 ],
          "approach_distance": [0, 0, -0.1],
          "tool": "tip"
      }]
  }
