coe_hw:
  type: "itia/control/CoeHwIfaceNodelet"
  soem_ns: "/cybersort_master/coe"
  sampling_period: 0.001
  coe_ros_plugins:
  - name: linear_motor_cursor_joint
    type: "coe_hw_plugins::DS402Complete"
    address: 11



