coe_hw:
  remap_source_args:
  - "/coe_hw/js_pub/joint_states"
  remap_target_args:
  - "/elmo/joint_states"
  js_pub:
    type: cnr/control/JointStatePublisher
    controlled_joint: all
    base_link: world
    tool_link: ur5_tool0
    robot_description_param: /robot_description
    robot_description_planning_param: /robot_description_planning

  ctrl0:
    type: cnr/control/OpenLoopPositionController
    setpoint_topic_name: "/ur5/joint_target"
    controlled_joint: "linear_motor_cursor_joint"
    enable_setpoint_watchdog: false

