ur5_hw:
  remap_source_args:
  - "/ur5_hw/js_pub/joint_states"
  remap_target_args:
  - "/ur5/joint_states"

  js_pub:
    type: cnr/control/JointStatePublisher
    controlled_joint: all
    base_link: ur5_base_link
    tool_link: ur5_tool0
    robot_description_param: /robot_description
    robot_description_planning_param: /robot_description_planning


  force_torque_sensor_controller:
     type:         force_torque_sensor_controller/ForceTorqueSensorController
     publish_rate: 125

  ctrl1:
    type:        cnr/control/OpenLoopPositionController
    setpoint_topic_name: "/ur5/joint_target"
    controlled_joints: all
    enable_setpoint_watchdog: false
