# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
- {id: 0, size: 0.072}
- {id: 1, size: 0.072}
- {id: 2, size: 0.072}
- {id: 3, size: 0.072}
- {id: 4, size: 0.072}
- {id: 5, size: 0.072}
- {id: 12, size: 0.072}
- {id: 13, size: 0.072}
- {id: 14, size: 0.072}
- {id: 15, size: 0.072}
- {id: 16, size: 0.036}
- {id: 24, size: 0.036}
- {id: 25, size: 0.036}
- {id: 26, size: 0.036}
- {id: 27, size: 0.036}
- {id: 28, size: 0.036}
- {id: 48, size: 0.036}
- {id: 49, size: 0.036}
- {id: 50, size: 0.036}
- {id: 51, size: 0.036}
- {id: 52, size: 0.036}
#- {id: , size: 0.06}
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
tag_bundles:
- name: 'cont1'
  layout:
  - {id: 24, size: 0.036, x: 0.00, y: 0,     z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 48, size: 0.036, x: 0.0, y: -0.45,     z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
- name: 'cont2'
  layout:
  - {id: 25, size: 0.036, x: 0.00, y: 0,     z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 49, size: 0.036, x: 0.0, y: -0.45,     z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
- name: 'cont3'
  layout:
  - {id: 26, size: 0.036, x: 0.00, y: 0,     z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 50, size: 0.036, x: 0.0, y: -0.45,     z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
- name: 'cont4'
  layout:
  - {id: 27, size: 0.036, x: 0.00, y: 0,     z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 51, size: 0.036, x: 0.0, y: -0.45,     z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
- name: 'cont5'
  layout:
  - {id: 28, size: 0.036, x: 0.00, y: 0,     z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 52, size: 0.036, x: 0.0, y: -0.45,     z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
- name: 'bundle_tabletop'
  layout:
  - {id: 0, size: 0.072, x: 0.00, y: 0,     z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 1, size: 0.072, x: 0.09, y: 0,     z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 2, size: 0.072, x: 0.18, y: 0,     z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 3, size: 0.072, x: 0.00, y: -0.09, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 4, size: 0.072, x: 0.09, y: -0.09, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 5, size: 0.072, x: 0.18, y: -0.09, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
- name: 'obj1_tag'
  layout:
  - {id: 12, size: 0.072, x: 0.00,  y: 0,      z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 13, size: 0.072, x: 0.117, y: 0,      z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 14, size: 0.072, x: 0.0,   y: -0.117, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 15, size: 0.072, x: 0.117, y: -0.117, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
- name: 'calibration'
  layout:
  - {id: 6, size: 0.072, x: 0.00, y: 0,     z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 7, size: 0.072, x: 0.09, y: 0,     z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 8, size: 0.072, x: 0.18, y: 0,     z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 9, size: 0.072, x: 0.00, y: -0.09, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 10, size: 0.072, x: 0.09, y: -0.09, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
  - {id: 11, size: 0.072, x: 0.18, y: -0.09, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
#tag_bundles:
  #[
  #]
