controller_list:
  - name: ur5
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - linear_motor_cursor_joint
      - ur5_shoulder_pan_joint
      - ur5_shoulder_lift_joint
      - ur5_elbow_joint
      - ur5_wrist_1_joint
      - ur5_wrist_2_joint
      - ur5_wrist_3_joint
